services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: vigilate-user
      POSTGRES_PASSWORD: vigilate-password
      POSTGRES_DB: vigilate-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .env.docker:/app/.env
    environment:
      - APP_ENV=docker
    depends_on:
      - postgres
      - kafka
      - ipe
    networks:
      - default

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - default

  ipe:
    image: riannegreiros/ipe:latest
    ports:
      - '4001:4001'
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - default

volumes:
  postgres-data:
    driver: local

networks:
  default:
    name: vigilate-network
    driver: bridge
