CREATE TABLE IF NOT EXISTS preferences (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  preference TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);